server:
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true
  port: 9090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
  http:
    encoding:
      charset: UTF-8
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  mapper-locations: com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity
